<?php

namespace AppBundle\Repository;

/**
 * DocNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
