<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Hierarchy;

/**
 * HierarchyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HierarchyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return Hierarchy[]
     */
    public function getGroup($id)
    {
        return $this->findBy(['id' => $id]);
    }
}
