<?php

namespace AppBundle\Repository;

/**
 * HierarchyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HierarchyRepository extends \Doctrine\ORM\EntityRepository
{
}
