<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Hierarchy;

/**
 * HierarchyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HierarchyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $id
     * @return Hierarchy[]
     */
    public function getGroup($id)
    {
        return $this->findBy(['id' => $id]);
    }

    /**
     * @param int $id
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getGroupQuery($id)
    {
        return $this->createQueryBuilder('u')
            ->where('u.id = ?1')
            ->setParameter(1, $id);
    }
}
