<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;
use AppBundle\Entity\User;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @param string $text
     * @return array
     */
    public function filterByText(User $user, $text)
    {
        return $this->createQueryBuilder('u')
            ->select('u.id,u.code,u.description AS name,u.price,u.taxCode AS tax')
            ->where('u.user = ?1 AND u.code LIKE ?2 OR u.description LIKE ?2')
            ->setMaxResults(10)
            ->setParameters([
                1 => $user,
                2 => "%$text%",
            ])
            ->getQuery()
            ->getResult();
    }

    /**
     * @param Product $product
     * @return bool
     */
    public function existProduct(Product $product)
    {
        $prod = $this->findOneBy(['code' => $product->getCode(), 'user' => $product->getUser()]);

        if ($prod && $prod->getId() != $product->getId()) {
            return true;
        }

        return false;
    }
}
