<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Product $product
     * @return bool
     */
    public function existProduct(Product $product)
    {
        $prod = $this->findOneBy(['code' => $product->getCode(), 'user' => $product->getUser()]);

        if ($prod && $prod->getId() != $product->getId()) {
            return true;
        }

        return false;
    }
}
