# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 7
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 7
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$07$fVo0jWeU.G/dV.8TDJRDye0GL87XZt0i7ElsxHqC1zOnwo9SZ9Y1a
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$07$fVo0jWeU.G/dV.8TDJRDye0GL87XZt0i7ElsxHqC1zOnwo9SZ9Y1a
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~

            # This allows the user to login by submitting a username and password
            # Reference: http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                # The route name that the login form submits to
                check_path: security_login
                # The name of the route where the login form lives
                # When the user tries to access a protected page, they are redirected here
                login_path: security_login
                # Secure the login form against CSRF
                # Reference: http://symfony.com/doc/current/cookbook/security/csrf_in_login_form.html
                csrf_token_generator: security.csrf.token_manager

            logout:
                # The route name the user can go to in order to logout
                path: security_logout
                # The name of the route to redirect to after logging out
                target: security_login

    access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/system, roles: ROLE_SYSTEM }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY}
