<?php

namespace App\Repository;

use App\Entity\User;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @param string $text
     * @return array
     */
    public function filterByText(User $user, $text)
    {
        return $this->createQueryBuilder('u')
            ->select('u.id, u.document, u.nameRzs AS name')
            ->where('u.user = ?1 AND u.document LIKE ?2 OR u.nameRzs LIKE ?2')
            ->setMaxResults(10)
            ->setParameters([
                1 => $user,
                2 => "%$text%",
            ])
            ->getQuery()
            ->getResult();
    }
}
