<?php

namespace App\Repository;

/**
 * UserUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
