<?php

namespace App\Repository;

/**
 * UserTaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTaxRepository extends \Doctrine\ORM\EntityRepository
{
}
